import { expect } from "chai";
import { network } from "hardhat";

const { ethers } = await network.create();

describe("InsuranceFraudRegistry", function () {
    const claimHash = "0x" + "11".repeat(32);
    const predictionHash = "0x" + "22".repeat(32);

    async function deploy() {
        // Artifacts/types are regenerated by `hardhat compile`; keep this test
        // independent from a stale generated TypeChain declaration.
        const registry: any = await ethers.deployContract("InsuranceFraudRegistry");
        const [writer, unauthorized] = await ethers.getSigners();
        return { registry, writer, unauthorized };
    }

    it("deploys with the deployer as its authorized writer", async function () {
        const { registry, writer } = await deploy();
        expect(await registry.authorizedWriter()).to.equal(writer.address);
    });

    it("stores, retrieves, and verifies a claim hash", async function () {
        const { registry } = await deploy();
        await expect(registry.storeClaimHash(8, claimHash)).to.emit(registry, "ClaimHashStored");
        expect(await registry.getClaimHash(8)).to.equal(claimHash);
        expect(await registry.verifyClaimHash(8, claimHash)).to.equal(true);
        expect(await registry.verifyClaimHash(8, predictionHash)).to.equal(false);
    });

    it("stores, retrieves, and verifies a prediction hash independently", async function () {
        const { registry } = await deploy();
        await registry.storePredictionHash(3, predictionHash);
        expect(await registry.getPredictionHash(3)).to.equal(predictionHash);
        expect(await registry.verifyPredictionHash(3, predictionHash)).to.equal(true);
        expect(await registry.verifyPredictionHash(3, claimHash)).to.equal(false);
    });

    it("rejects unauthorized writes", async function () {
        const { registry, unauthorized } = await deploy();
        await expect(registry.connect(unauthorized).storeClaimHash(8, claimHash)).to.be.revertedWith("Unauthorized writer");
    });

    it("rejects duplicate records", async function () {
        const { registry } = await deploy();
        await registry.storeClaimHash(8, claimHash);
        await expect(registry.storeClaimHash(8, predictionHash)).to.be.revertedWith("Claim already registered");
        await registry.storePredictionHash(3, predictionHash);
        await expect(registry.storePredictionHash(3, claimHash)).to.be.revertedWith("Prediction already registered");
    });
});
